dataset001:
  template001:
    Forward_Primer_2ndRd_Sequence: GATCTACACTCTTTCCCTACACGAC
    Reverse_Primer_2ndRd_Sequence: AGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    sUMI_Primer_Sequence: actataNNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
    dUMI_Primer_Sequence: NNNNNNNNATAGCTGTCTTTTATC